language: node_js
node_js:
  - 13
services:
  - docker
install:
  - echo "install"
before_script:
  - echo "before_script"
script:
  - docker --version
  - docker build -t reverseproxy .
  - docker tag reverseproxy manhhong/reverseproxy:v1
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push manhhong/reverseproxy:v1
